### PR TITLE
 T816 ipaddrcheck / libcidr but on IPv6 network validation #2

### PR DESCRIPTION
**Pull request by EwaldvanGeffen**
I ran and extend the tests this time. I was a little to eager last night :)

### CODE REVIEW

**Comment by c-po** [comment]
Any possibility to squash/fixup commit 6d90a2ad0e65f58db08b42d6d7b4a74819be9888 into 
a4caa31362ba803ced565a87519b593411c1b32b as the latter removes the lines and the former readds them?

**Comment by EwaldvanGeffen** [comment]
@c-po my-first-rebase-ever 👍

**Comment by c-po** [comment]
Thank you for keeping the repository clean.

How did you actually compile it for testing? There is no `libcidr-dev` package on Debian Jessie. Did you use Debian buster?

**Comment by EwaldvanGeffen** [comment]
I compiled libcidr locally and make installed it (on a CentOS 7). IIRC I added a few symlinks from usr include to usr local include to get the runtime properly working.

**Comment by dmbaturin** [comment]
@EwaldvanGeffen I've added a simpler solution that is also more conductive to producing diagnostic messages: just check if "::" substring appears more than once.
Thanks for your effort though!

**Pull request closed without merging**
